version = 1

[[annotations]]
path = [
  ".gitignore",
  ".release-please-manifest.json",
  "go.mod",
  "go.sum",
  "release-please-config.json",
  "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "testdata/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"
