version = 1

[[annotations]]
path = [
  ".gitignore",
  "go.mod",
  "go.sum",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "testdata/**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Bonial International GmbH"
SPDX-License-Identifier = "Apache-2.0"
